
name: releases pub

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: gzip
        run: |
          chmod +x script/bash.sh
          ./script/bash.sh
      - name: Generate release tag
        id: tag
        shell: bash
        run: |
          chmod +x script/release.sh
          ./script/release.sh
      - name: Upload  to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: up/*
